"""initial schema

Revision ID: 4fda54299dc7
Revises: 
Create Date: 2026-09-05 01:18:46.782995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '4fda54299dc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_external_id'), 'agencies', ['external_id'], unique=True)
    op.create_table('contractors',
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('total_projects', sa.Integer(), nullable=False),
    sa.Column('completed_projects', sa.Integer(), nullable=False),
    sa.Column('delayed_projects', sa.Integer(), nullable=False),
    sa.Column('high_risk_projects', sa.Integer(), nullable=False),
    sa.Column('average_cost_overrun', sa.Float(), nullable=True),
    sa.Column('average_delay_days', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_external_id'), 'contractors', ['external_id'], unique=True)
    op.create_index(op.f('ix_contractors_normalized_name'), 'contractors', ['normalized_name'], unique=False)
    op.create_table('ingestion_reports',
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Integer(), nullable=False),
    sa.Column('invalid', sa.Integer(), nullable=False),
    sa.Column('missing_location', sa.Integer(), nullable=False),
    sa.Column('missing_contractor', sa.Integer(), nullable=False),
    sa.Column('missing_amount', sa.Integer(), nullable=False),
    sa.Column('duplicate_candidates', sa.Integer(), nullable=False),
    sa.Column('entity_matches', sa.Integer(), nullable=False),
    sa.Column('uncertain_matches', sa.Integer(), nullable=False),
    sa.Column('language_distribution', sa.JSON(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OFFICER', 'ANALYST', 'VIEWER', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('external_project_id', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('project_type', sa.Enum('ROAD', 'SCHOOL', 'COMMUNITY_HALL', 'WATER_INFRASTRUCTURE', 'HEALTH_CENTRE', 'SANITATION', 'PUBLIC_FACILITY', name='projecttype', native_enum=False, length=32), nullable=False),
    sa.Column('sub_type', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('constituency', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('sanctioned_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('released_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expenditure_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expected_completion_date', sa.Date(), nullable=False),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('physical_progress', sa.Float(), nullable=False),
    sa.Column('financial_progress', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('SANCTIONED', 'ONGOING', 'DELAYED', 'COMPLETED', name='projectstatus', native_enum=False, length=32), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('implementing_agency_id', sa.UUID(), nullable=True),
    sa.Column('name_embedding', Vector(dim=384), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['implementing_agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # idx_projects_geom is created automatically by GeoAlchemy2's DDL event when
    # the table is created (spatial_index=True is the Geometry column default).
    op.create_index(op.f('ix_projects_district'), 'projects', ['district'], unique=False)
    op.create_index(op.f('ix_projects_external_project_id'), 'projects', ['external_project_id'], unique=True)
    op.create_index(op.f('ix_projects_state'), 'projects', ['state'], unique=False)
    op.create_table('entity_matches',
    sa.Column('source_project_id', sa.UUID(), nullable=False),
    sa.Column('matched_project_id', sa.UUID(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('verdict', sa.Enum('MATCH', 'POSSIBLE_MATCH', 'DIFFERENT', name='matchverdict', native_enum=False, length=16), nullable=False),
    sa.Column('matching_features', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_matches_matched_project_id'), 'entity_matches', ['matched_project_id'], unique=False)
    op.create_index(op.f('ix_entity_matches_source_project_id'), 'entity_matches', ['source_project_id'], unique=False)
    op.create_table('evidence',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PHOTO', 'DOCUMENT', 'INSPECTION_REPORT', 'INVOICE', name='evidencetype', native_enum=False, length=32), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_hash'), 'evidence', ['hash'], unique=False)
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_table('investigations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='investigationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Enum('LEGITIMATE', 'NEEDS_FURTHER_INVESTIGATION', 'ISSUE_CONFIRMED', 'INSUFFICIENT_DATA', name='investigationresolution', native_enum=False, length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_project_id'), 'investigations', ['project_id'], unique=False)
    op.create_table('milestones',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('expected_progress', sa.Float(), nullable=False),
    sa.Column('actual_progress', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ON_TRACK', 'DELAYED', 'COMPLETED', name='milestonestatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    op.create_table('payments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_type', sa.Enum('ADVANCE', 'MILESTONE', 'FINAL', name='paymenttype', native_enum=False, length=32), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'CLEARED', 'FAILED', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('transaction_reference', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_project_id'), 'payments', ['project_id'], unique=False)
    op.create_table('risk_signals',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('PAYMENT_PROGRESS_MISMATCH', 'COST_ANOMALY', 'DELAY_ANOMALY', 'POSSIBLE_DUPLICATE', 'CONTRACTOR_RISK_PATTERN', 'GEOGRAPHIC_CONCENTRATION', 'PAYMENT_ACCELERATION', 'PROGRESS_INCONSISTENCY', 'EVIDENCE_ANOMALY', 'ML_STATISTICAL_ANOMALY', 'MULTI_SIGNAL_CORRELATION', name='signaltype', native_enum=False, length=64), nullable=False),
    sa.Column('source', sa.Enum('RULE', 'ML', 'CORRELATED', name='signalsource', native_enum=False, length=16), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_project_id'), 'risk_signals', ['project_id'], unique=False)
    op.create_table('inspections',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('inspector', sa.String(length=255), nullable=True),
    sa.Column('reported_progress', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('evidence_reference', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_reference'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_project_id'), 'inspections', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspections_project_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_risk_signals_project_id'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_payments_project_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_investigations_project_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_hash'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_entity_matches_source_project_id'), table_name='entity_matches')
    op.drop_index(op.f('ix_entity_matches_matched_project_id'), table_name='entity_matches')
    op.drop_table('entity_matches')
    op.drop_index(op.f('ix_projects_state'), table_name='projects')
    op.drop_index(op.f('ix_projects_external_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_district'), table_name='projects')
    op.drop_index('idx_projects_geom', table_name='projects', postgresql_using='gist')
    op.drop_table('projects')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ingestion_reports')
    op.drop_index(op.f('ix_contractors_normalized_name'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_external_id'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_agencies_external_id'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
