"""add project risk_score and risk_band

Revision ID: 961bbb6bdd39
Revises: 4fda54299dc7
Create Date: 2026-09-05 12:41:24.879048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961bbb6bdd39'
down_revision: Union[str, None] = '4fda54299dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('risk_band', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity', native_enum=False, length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'risk_band')
    op.drop_column('projects', 'risk_score')
    # ### end Alembic commands ###
